pipeline:
  build:
    image: docker.io/logicalhacking/isabelle2022
    commands:
      - export ARTIFACT_DIR=$CI_WORKSPACE/.artifacts/$CI_REPO/$CI_BRANCH/$CI_BUILD_NUMBER/
      - mkdir -p $ARTIFACT_DIR
      - export `isabelle getenv ISABELLE_HOME_USER`
      - isabelle build -D . -o browser_info
      - cp -r $ISABELLE_HOME_USER/browser_info $ARTIFACT_DIR
      - cp output/document.pdf $ARTIFACT_DIR
      - cd $ARTIFACT_DIR
      - cd ..
      - ln -s * latest
  deploy:
    image: docker.io/drillster/drone-rsync
    settings:
      hosts: [ "ci.logicalhacking.com"]
      port: 22
      source: .artifacts/$CI_REPO_OWNER/*
      target: $CI_REPO_OWNER
      include: [ "**.*"]
      key:
        from_secret: artifacts_ssh
      user: artifacts
  notify:
    image: drillster/drone-email
    settings:
      host: smtp.0x5f.org
      username: woodpecker
      password: 
        from_secret: email
      from: ci@logicalhacking.com
    when:
      status: [ changed, failure ]    
